on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setear variable
        run: |
              export ALGO=$(cat archivo | xargs)

      - name: Ver variable
        run: |
              env | grep ALGO

      - name: Usar
        run: |
              mkdir ${ALGO}
              ls
